// <auto-generated />
using System;
using LH.Date.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LH.Date.Migrations
{
    [DbContext(typeof(AppRhContext))]
    [Migration("20230313013651__bancoInicial")]
    partial class _bancoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LH.Business.Models.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnoVigencia");

                    b.Property<string>("MesVigencia")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeDepartamento")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("TotalDescontos");

                    b.Property<decimal>("TotalExtras");

                    b.Property<decimal>("TotalPagar");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("LH.Business.Models.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Codigo");

                    b.Property<Guid>("DepartamentoId");

                    b.Property<int>("DiasExtras");

                    b.Property<int>("DiasFalta");

                    b.Property<int>("DiasTrabalhados");

                    b.Property<double>("HorasDebito");

                    b.Property<double>("HorasExtras");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("TotalReceber");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("LH.Business.Models.RegistroPonto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Almoco");

                    b.Property<int>("Codigo");

                    b.Property<DateTime>("Data");

                    b.Property<DateTime>("Entrada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Saida");

                    b.Property<decimal>("ValorHora");

                    b.HasKey("Id");

                    b.ToTable("RegistroPontos");
                });

            modelBuilder.Entity("LH.Business.Models.Funcionario", b =>
                {
                    b.HasOne("LH.Business.Models.Departamento", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoId");
                });
#pragma warning restore 612, 618
        }
    }
}
